import type { GameDataModel } from "../domain/GameDataModel";

export const dataModel: GameDataModel = [
  {
    name: "powers",
    title: "Силы",
    type: "list",
    initialLength: 10,
    maxLength: 15,
    proto: {
      type: "labeledNumber",
      label: "",
      value: 1,
      min: 1,
      max: 3,
    },
  },
  {
    name: "dreamlandPowers",
    title: "Силы Мира Грёз",
    type: "list",
    initialLength: 3,
    maxLength: 3,
    proto: {
      type: "labeledNumber",
      label: "",
      value: 1,
      min: 1,
      max: 3,
    },
  },
  {
    name: "weakness",
    title: "Слабость",
    type: "labeledNumber",
    label: "",
    value: 1,
    min: 1,
    max: 5,
  },
  {
    name: "recollections",
    title: "Воспоминания",
    type: "list",
    initialLength: 2,
    maxLength: 3,
    proto: {
      type: "labeledNumber",
      label: "",
      value: 1,
      min: 1,
      max: 6,
    },
  },
  {
    name: "mentalConditions",
    title: "Душевные состояния",
    type: "list",
    initialLength: 3,
    maxLength: 3,
    proto: {
      type: "characterCondition",
      label: "",
      value: 1,
      isInjury: false,
    },
  },
  {
    name: "bodyWounds",
    title: "Телесные раны",
    type: "list",
    initialLength: 3,
    maxLength: 6,
    proto: {
      type: "characterCondition",
      label: "",
      value: 1,
      isInjury: false,
    },
  },
  {
    name: "temporalConditions",
    title: "Трудности и преимущества",
    type: "list",
    initialLength: 3,
    proto: {
      type: "labeledNumber",
      label: "",
      value: 1,
    },
  },
  {
    name: "luck",
    title: "Удача",
    type: "number",
    value: 0,
    min: 0,
    max: 12,
  },
  {
    name: "items",
    title: "Снаряжение",
    type: "list",
    initialLength: 3,
    proto: {
      type: "gearItem",
      label: "",
      currentStrength: 0,
      maxStrength: 0,
      powers: [],
    },
  },
  {
    name: "projects",
    title: "Замыслы",
    type: "list",
    initialLength: 2,
    proto: {
      type: "project",
      label: "",
      progress: 0,
      successThreshold: 0,
      description: "",
    },
  },
  {
    name: "notes",
    title: "Заметки",
    type: "string",
    value: "",
  },
];
