import type { GameDataModel } from "../domain/GameDataModel";

export const dataModel: GameDataModel = [
  {
    id: "powers",
    name: "Силы",
    type: "list",
    initialLength: 10,
    maxLength: 15,
    proto: {
      type: "labeledNumberInRange",
      label: "",
      value: 1,
      min: 1,
      max: 3,
    },
  },
  {
    id: "dreamlandPowers",
    name: "Силы Мира Грёз",
    type: "list",
    initialLength: 3,
    maxLength: 3,
    proto: {
      type: "labeledNumberInRange",
      label: "",
      value: 1,
      min: 1,
      max: 3,
    },
  },
  {
    id: "weakness",
    name: "Слабость",
    type: "labeledNumberInRange",
    label: "",
    value: 1,
    min: 1,
    max: 5,
  },
  {
    id: "recollections",
    name: "Воспоминания",
    type: "list",
    initialLength: 2,
    maxLength: 3,
    proto: {
      type: "labeledNumberInRange",
      label: "",
      value: 1,
      min: 1,
      max: 6,
    },
  },
  {
    id: "mentalConditions",
    name: "Душевные состояния",
    type: "list",
    initialLength: 3,
    maxLength: 3,
    proto: {
      type: "characterCondition",
      label: "",
      value: 1,
      isInjury: false,
    },
  },
  {
    id: "bodyWounds",
    name: "Телесные раны",
    type: "list",
    initialLength: 3,
    maxLength: 6,
    proto: {
      type: "characterCondition",
      label: "",
      value: 1,
      isInjury: false,
    },
  },
  {
    id: "temporalConditions",
    name: "Трудности и преимущества",
    type: "list",
    initialLength: 3,
    proto: {
      type: "labeledNumber",
      label: "",
      value: 1,
    },
  },
  {
    id: "luck",
    name: "Удача",
    type: "number",
    value: 0,
    min: 0,
    max: 12,
  },
  {
    id: "items",
    name: "Снаряжение",
    type: "list",
    initialLength: 3,
    proto: {
      type: "gearItem",
      label: "",
      currentStrength: 0,
      maxStrength: 0,
      powers: [],
    },
  },
  {
    id: "projects",
    name: "Замыслы",
    type: "list",
    initialLength: 2,
    proto: {
      type: "project",
      label: "",
      progress: 0,
      successThreshold: 0,
      description: "",
    },
  },
  {
    id: "notes",
    name: "Заметки",
    type: "string",
    value: "",
  },
];
